# 4. Probando Numpy y Pandas
#### a. ¿Campo de aplicación de las librerías Pandas y Numpy?
NumPy y Pandas son las librerías de python ideales para análisis de datos y computación numérica. Seguramente también nos enfrentaremos a problemas que no requieren el uso de aprendizaje automático sino sólo el análisis de datos. Por supuesto, también podemos usar estas librerías en estos casos.
#### b. Utilizando la hoja de trucos de Numpy, pruebe cada uno de los códigos y 
muestre los resultados de cada sección:
##### Creando arrays


In [4]:
import numpy as np
a = np.array([1,2,3])
b = np.array([(1.5,2,3), (4,5,6)], dtype = float)
c = np.array([[(1.5,2,3), (4,5,6)], [(3,2,1), (4,5,6)]], dtype = float)

### Creando arrays de ceros 

In [10]:
np.zeros((3,4)) 


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### Creando arrays de uno

In [12]:
np.ones((2,3,4),dtype=np.int16)

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

### Creando arrays igualado

In [17]:
d = np.arange(10,25,5)

In [19]:
 np.linspace(0,2,9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

### Creando arrays constantes, arays con valores random, y de matrices

In [20]:
e = np.full((2,2),7) 
f = np.eye(2)

In [22]:
np.random.random((2,2))

array([[0.23652508, 0.510818  ],
       [0.73496005, 0.10276855]])

In [23]:
 np.empty((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

### Guardado y cargado de disco

In [24]:
np.save('my_array', a)
np.savez('array.npz', a, b)
np.load('my_array.npy')

array([1, 2, 3])

### Guardado y cargado de archivos de texto

In [6]:
np.loadtxt("myfile.txt")
np.genfromtxt("my_file.csv", delimiter=',')
np.savetxt("myarray.txt", a, delimiter=" ")

NameError: name 'np' is not defined

# Tipos de datos

In [32]:
np.int64 ##prueba de entero de 64 bits

numpy.int64

In [33]:
np.float32 ##prueba de coma flotante de 32

numpy.float32

In [37]:
np.complex128 ##este nos permite usar valores de tipo coma flotante de mas de 128 bits

numpy.complex128

In [41]:
np.bool_ ## valores boleanos que nos permite mostrar valores de verdarero y falso

numpy.bool_

In [44]:
object ## de tipo objeto

object

In [45]:
np.string_ ## de tipo string nos permite hacer cadenas

numpy.bytes_

In [47]:
np.unicode_ ##usando codigo de un mismo tipo

numpy.str_

### Inspeccion de arrays

In [27]:
a.shape 
len(a) 
b.ndim 
e.size
b.dtype
b.dtype.name
b.astype(int) 

array([[1, 2, 3],
       [4, 5, 6]])

# Pidiendo ayuda

In [48]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>


# arrays matematicos, operaciones aritmeticas

In [52]:
 g = a - b ##sustraccion
 ([[-0.5, 0. , 0. ],
 [-3. , -3. , -3. ]])

[[-0.5, 0.0, 0.0], [-3.0, -3.0, -3.0]]

In [53]:
np.subtract(a,b) 

array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [61]:
b + a ##Adicion de arrays
([[ 2.5, 4. , 6. ],
[ 5. , 7. , 9. ]])
np.add(b,a) 

array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [62]:
a / b ##Division
([[ 0.66666667, 1. , 1. ],
[ 0.25 , 0.4 , 0.5 ]])
np.divide(a,b)

array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [64]:
a * b ##Multiplication
([[ 1.5, 4. , 9. ],
[ 4. , 10. , 18. ]])
np.multiply(a,b)

array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

In [65]:
np.exp(b) ##Exponenciacion

array([[  4.48168907,   7.3890561 ,  20.08553692],
       [ 54.59815003, 148.4131591 , 403.42879349]])

In [67]:
np.sqrt(b) ## raiz cuadrada

array([[1.22474487, 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [69]:
 np.sin(a) ##imprimir senos de una matriz

array([0.84147098, 0.90929743, 0.14112001])

In [70]:
 np.cos(b) ##coseno de elementos

array([[ 0.0707372 , -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029]])

In [71]:
 np.log(a) ##logaritmo natural por elementos

array([0.        , 0.69314718, 1.09861229])

In [73]:
 e.dot(f) ##Dot product
([[ 7., 7.],
[ 7., 7.]])

array([[7., 7.],
       [7., 7.]])

# Comparaciones

In [75]:
a == b ##Comparación de elementos

array([[False,  True,  True],
       [False, False, False]])

In [76]:
a < 2 ##

array([ True, False, False])

In [77]:
 np.array_equal(a, b) ## arrays de comparaciond e elementos

False

# Agregar funciones

In [78]:
 a.sum() #sumamos los arreglos

6

In [79]:
a.min() #Matris de valor minimo

1

In [80]:
b.max(axis=0) #valor máximo de una fila de matriz

array([4., 5., 6.])

In [81]:
b.cumsum(axis=1) #suma acumulativa de los elementos

array([[ 1.5,  3.5,  6.5],
       [ 4. ,  9. , 15. ]])

In [82]:
a.mean() #media

2.0

In [139]:
np.median(b)

3.5

In [142]:
np.corrcoef(a)

1.0

In [92]:
np.std(b) #desviacion standard

1.5920810978785667

# Copiar matrices

In [94]:
h = a.view() #crear una vista de la matriz con los mismos datos

In [96]:
np.copy(a) #creamos la copia del array

array([1, 2, 3])

In [97]:
h = a.copy() # creando copia profunda de la matriz

# Ordenación de matrices


In [98]:
 a.sort() 

In [99]:
 c.sort(axis=0) 

# Subconjunto, rebanado, indexación

In [101]:
 a[2] #elija el elemento en el segundo índice Esto es un subconjuto

3

In [103]:
 b[1,2] #elija el elemento en la fila 1 columna 2(equivalente a b [1] [2])

6.0

In [104]:
#Esto es un rebanado
a[0:2] #elegir elementos en el índice 0 y 1

array([1, 2])

In [105]:
 b[0:2,1] #elegir elementos en las filas 0 y 1 en la columna 1

array([2., 5.])

In [106]:
 b[:1]  #Seleccionar todos los elementos de la fila 0

array([[1.5, 2. , 3. ]])

In [107]:
 c[1,...] #Lo mismo que [1,:,:]

array([[3., 2., 3.],
       [4., 5., 6.]])

In [108]:
 a[ : :-1] #Matriz invertida a

array([3, 2, 1])

# Indexación booleana

In [109]:
 a[a<2]  #Seleccione elementos de menos de 2

array([1])

# Indexación elegante

In [110]:
 b[[1, 0, 1, 0],[0, 1, 2, 0]] 

array([4. , 2. , 6. , 1.5])

In [111]:
 b[[1, 0, 1, 0]][:,[0,1,2,0]] 

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

# Manipulación de matrices

In [113]:
#Transposición de matriz
i = np.transpose(b) #Permutar las dimensiones de la matriz
i.T

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [116]:
#Cambiar la forma de la matriz
b.ravel() #Aplanar la matriz

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [117]:
g.reshape(3,-2) #Dale nueva forma, pero no cambies los datos

array([[-0.5,  0. ],
       [ 0. , -3. ],
       [-3. , -3. ]])

In [120]:
#Agregar / eliminar elementos
h.resize((2,6)) #Devuelve una nueva matriz con forma (2,6)

In [121]:
 np.append(h,g) #Agregar elementos a una matriz

array([ 1. ,  2. ,  3. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,
        0. , -0.5,  0. ,  0. , -3. , -3. , -3. ])

In [122]:
 np.insert(a, 1, 5) #Insertar elementos en una matriz

array([1, 5, 2, 3])

In [123]:
np.delete(a,[1]) #Eliminar elementos de una matriz

array([1, 3])

# Combinando matrices

In [124]:
np.concatenate((a,d),axis=0) #Concatenar matrices

array([ 1,  2,  3, 10, 15, 20])

In [125]:
np.vstack((a,b)) #Apilar matrices verticalmente (por filas)

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [126]:
np.r_[e,f]  #Stack arrays vertically (row-wise)

array([[7., 7.],
       [7., 7.],
       [1., 0.],
       [0., 1.]])

In [127]:
np.hstack((e,f)) # Apilar matrices horizontalmente (en columnas)

array([[7., 7., 1., 0.],
       [7., 7., 0., 1.]])

In [128]:
np.column_stack((a,d)) #Cree matrices apiladas en columnas

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

In [129]:
 np.c_[a,d] #Create stacked column-wise arrays

array([[ 1, 10],
       [ 2, 15],
       [ 3, 20]])

# División de matrices

In [130]:
 np.hsplit(a,3)  #Divida la matriz horizontalmente en el tercer índice

[array([1]), array([2]), array([3])]

In [131]:
np.vsplit(c,2)  #Divida la matriz verticalmente en el segundo índice

[array([[[1.5, 2. , 1. ],
         [4. , 5. , 6. ]]]),
 array([[[3., 2., 3.],
         [4., 5., 6.]]])]